title: Mahmoud Kargar
description: Personal Website – Research, Reflections, and Projects
logo: /assets/images/profile.jpg  # ← عکست رو بعداً اینجا قرار بده
theme: jekyll-theme-minimal
google_analytics: false

# Optional social links (در صفحه اصلی نمایش داده نمی‌شه اما قابل استفاده‌ست)
social_links:
  scholar: https://scholar.google.com/citations?hl=en&user=VTDvJ4kAAAAJ
  researchgate: https://www.researchgate.net/profile/Mahmoud-Kargar
  linkedin: https://www.linkedin.com/in/kargarm/
