title: Mahmoud Kargar
description: Personal Website - Research, Reflections, and Projects
logo: /assets/images/profile.jpg
theme: jekyll-theme-minimal
google_analytics: false
url: "https://mkargar-2025.github.io"
baseurl: ""
permalink: pretty

social_links:
  scholar: https://scholar.google.com/citations?user=VTDvJ4kAAAAJ
  researchgate: https://www.researchgate.net/profile/Mahmoud-Kargar
  linkedin: https://www.linkedin.com/in/kargarm/


